server:
  port: 8888

## thymeleaf template engine configure
spring:
  thymeleaf:
    suffix: .html
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML
    check-template-location: true
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

tio:
  websocket:
    server:
      # websocket port default 9876
      port: 6789
      # 心跳时间
      heartbeat-timeout: 60000
      # 监控时段,多个之间用逗号隔开
      ip-stat-durations: [60]
    # 集群配置 默认关闭
    cluster:
      enabled: false
      # 集群是通过redis的Pub/Sub实现，所以需要配置Redis
      redis:
        #集群模式
        #mode: cluster
        #config-path: redis-cluster-config.json
        # 哨兵模式
        #mode: sentinel
        #config-path: redis-sentinel-config.json
        # 单机模式
        mode: single
        ip: 127.0.0.1
        port: 6379
      all: true
      group: true
      ip: true
      user: true
      # SSL 配置
      ssl:
        enabled: false
        key-store:
        password:
        trust-store:
